name: Typos

on:
  push:
    branches: [main, website-rewrite]
  pull_request:
    branches: [main, website-rewrite]

jobs:
  typos:
    name: Check for typos
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.36.2
